# In-Class Lab: Neural Networks

In this lab, we will implement a neural network to solve the XOR problem.  For now, we will only implement the predict method, given weights that have been pre-computed (that were extracted from an already trained network).

The architecture of the network would be similar to the main example we 
showed in class:

* Input layer: 2 neurons (for the two inputs of XOR function)

* Hidden layer: 3 neurons (we will have only 1 hidden layer with three neurons)

* Output layer: 1 neuron (1 neuron in the output as output will be a single digit (0 or 1))




# Part 1: Setup & Initialization

In [ ]:
import numpy as np

# helper function to implement tanh
def tanh(x): 
  return np.tanh(x)

## Initializing the weights for the different layers of the network

In [ ]:
# weights for the layer between the inputs and the hidden layer
weights_l1 = (np.reshape([1.33802204,  0.27270439, -2.32711844,1.06193803,  0.77875626, -2.36624024], (2,3)))

# weights for the layer between the hidden layer and the output layer
weights_l2 = [[-2.16869671], [-1.09397363], [-2.61705925]]

# concatenating all the weights in the neural network together
weights = [weights_l1, np.array(weights_l2)]
weights

[array([[ 1.33802204,  0.27270439, -2.32711844],
        [ 1.06193803,  0.77875626, -2.36624024]]), array([[-2.16869671],
        [-1.09397363],
        [-2.61705925]])]

In [ ]:
# bias weights for the nodes in the hidden layer
bias_l1 = [-1.71269062, -0.40820044,  0.81479502]

# bias weights for the output layer node
bias_l2 = [-0.69492816]

# concatenating all the bias values in the neural network together
bias = [np.array([bias_l1]), np.array([bias_l2])]
bias

[array([[-1.71269062, -0.40820044,  0.81479502]]), array([[-0.69492816]])]

### Exercise 1: Compute the vector of activations that is output by a network layer

Hint: Use the np.dot function, and tanh activation.

In [ ]:
def compute_activation(input, weights, bias):
  result = np.dot(input, weights) + bias

  return tanh(result)

### Exercise 2: Compute a full forward propagation pass

In [ ]:
# use the neural network to make predictions for each sample in the test data
def predict(test_data):
        
        result = []

        for i in range(len(test_data)):
            
            # compute the vector of activations output by the hidden layer
            output1_activation = compute_activation(test_data[i], weights_l1, bias_l1)
            print('output1_activation:', output1_activation)
            # compute the activatiion output by the output layer (the single output neuron)
            output2_activation = compute_activation(output1_activation, weights_l2, bias_l2)
            print('output2_activation:', output2_activation)

            result.append(output2_activation)

        return result

In [ ]:
# use the neural network to make predictions for each sample in the test data
def predict(test_data):
        
        result = []

        for i in range(len(test_data)):
            
            # compute the vector of activations output by the hidden layer
            output1_activation = compute_activation(test_data[i], weights_l1, bias_l1)
            print('output1_activation:', output1_activation)
            # compute the activatiion output by the output layer (the single output neuron)
            output2_activation = compute_activation(output1_activation, weights_l2, bias_l2)
            print('output2_activation:', output2_activation)

            result.append(output2_activation)

        return result

In [ ]:
x_test = np.array([[[0,0]], [[0,1]], [[1,0]], [[1,1]]])
x_test[0]

array([[0, 0]])

In [ ]:
# predict the first test sample
prediction = predict(x_test[0])
prediction

output1_activation: [-0.93697683 -0.38694363  0.67222694]
output2_activation: [0.00113879]


[array([0.00113879])]

In [ ]:
# predict all test samples
predictions = predict(x_test)
predictions

output1_activation: [[-0.93697683 -0.38694363  0.67222694]]
output2_activation: [[0.00113879]]
output1_activation: [[-0.57217639  0.35447779 -0.91402363]]
output2_activation: [[0.98788554]]
output1_activation: [[-0.35806851 -0.1346729  -0.9073505 ]]
output2_activation: [[0.98910423]]
output1_activation: [[ 0.59622498  0.5671153  -0.999145  ]]
output2_activation: [[0.00645307]]


[array([[0.00113879]]),
 array([[0.98788554]]),
 array([[0.98910423]]),
 array([[0.00645307]])]

In [ ]:
# predict all test samples
predictions = predict(x_test)
predictions

[array([[0.00113879]]),
 array([[0.98788554]]),
 array([[0.98910423]]),
 array([[0.00645307]])]